from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addPasswordDialog(object):
    def setupUi(self, addPasswordDialog):
        addPasswordDialog.setObjectName("addPasswordDialog")
        addPasswordDialog.setFixedSize(1050, 465)
        addPasswordDialog.setStyleSheet("background-color: rgb(85, 170, 255); color: rgb(255, 255, 255);")
        addPasswordDialog.setWindowFlag(QtCore.Qt.WindowContextHelpButtonHint, False)   #hide "?"
        addPasswordDialog.setWindowIcon(QtGui.QIcon('sources\window_icon.ico'))

        self.accountCreationDate_text = QtWidgets.QLabel(addPasswordDialog)
        self.accountCreationDate_text.setGeometry(QtCore.QRect(10, 260, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.accountCreationDate_text.setFont(font)
        self.accountCreationDate_text.setObjectName("accountCreationDate_text")

        self.eMail_text = QtWidgets.QLabel(addPasswordDialog)
        self.eMail_text.setGeometry(QtCore.QRect(380, 100, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.eMail_text.setFont(font)
        self.eMail_text.setObjectName("eMail_text")

        self.email_lineEdit = QtWidgets.QLineEdit(addPasswordDialog)
        self.email_lineEdit.setGeometry(QtCore.QRect(380, 130, 491, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.email_lineEdit.setFont(font)
        self.email_lineEdit.setText("")
        self.email_lineEdit.setObjectName("email_lineEdit")

        self.username_lineEdit = QtWidgets.QLineEdit(addPasswordDialog)
        self.username_lineEdit.setGeometry(QtCore.QRect(10, 130, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.username_lineEdit.setFont(font)
        self.username_lineEdit.setText("")
        self.username_lineEdit.setObjectName("username_lineEdit")

        self.username_text = QtWidgets.QLabel(addPasswordDialog)
        self.username_text.setGeometry(QtCore.QRect(10, 100, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.username_text.setFont(font)
        self.username_text.setObjectName("username_text")

        self.appName_lineEdit = QtWidgets.QLineEdit(addPasswordDialog)
        self.appName_lineEdit.setGeometry(QtCore.QRect(10, 210, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.appName_lineEdit.setFont(font)
        self.appName_lineEdit.setText("")
        self.appName_lineEdit.setObjectName("appName_lineEdit")

        self.password_lineEdit = QtWidgets.QLineEdit(addPasswordDialog)
        self.password_lineEdit.setGeometry(QtCore.QRect(380, 210, 491, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.password_lineEdit.setFont(font)
        self.password_lineEdit.setText("")
        self.password_lineEdit.setObjectName("password_lineEdit")

        self.password_text = QtWidgets.QLabel(addPasswordDialog)
        self.password_text.setGeometry(QtCore.QRect(380, 180, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.password_text.setFont(font)
        self.password_text.setObjectName("password_text")

        self.appName_text = QtWidgets.QLabel(addPasswordDialog)
        self.appName_text.setGeometry(QtCore.QRect(10, 180, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.appName_text.setFont(font)
        self.appName_text.setObjectName("appName_text")

        self.feedback_label = QtWidgets.QLabel(addPasswordDialog)
        self.feedback_label.setGeometry(QtCore.QRect(370, 340, 681, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.feedback_label.setFont(font)
        self.feedback_label.setObjectName("feedback_label")

        self.save_pushButton = QtWidgets.QPushButton(addPasswordDialog)
        self.save_pushButton.setGeometry(QtCore.QRect(400, 300, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.save_pushButton.setFont(font)
        self.save_pushButton.setObjectName("save_pushButton")

        self.clear_pushButton = QtWidgets.QPushButton(addPasswordDialog)
        self.clear_pushButton.setGeometry(QtCore.QRect(540, 300, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.clear_pushButton.setFont(font)
        self.clear_pushButton.setObjectName("clear_pushButton")
        self.clear_pushButton.hide()

        self.add_a_password_text = QtWidgets.QLabel(addPasswordDialog)
        self.add_a_password_text.setGeometry(QtCore.QRect(10, 20, 301, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.add_a_password_text.setFont(font)
        self.add_a_password_text.setObjectName("add_a_password_text")

        self.line = QtWidgets.QFrame(addPasswordDialog)
        self.line.setGeometry(QtCore.QRect(320, 40, 841, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        self.creation_date_dateEdit = QtWidgets.QDateEdit(addPasswordDialog)
        self.creation_date_dateEdit.setGeometry(QtCore.QRect(10, 290, 211, 41))
        self.creation_date_dateEdit.setDisplayFormat("d/M/yyyy")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.creation_date_dateEdit.setFont(font)
        self.creation_date_dateEdit.setCalendarPopup(True)
        self.creation_date_dateEdit.setObjectName("creation_date_dateEdit")

        self.enable_disable_dare_pushButton = QtWidgets.QPushButton(addPasswordDialog)
        self.enable_disable_dare_pushButton.setGeometry(QtCore.QRect(240, 290, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.enable_disable_dare_pushButton.setFont(font)
        self.enable_disable_dare_pushButton.setObjectName("enable_disable_dare_pushButton")

        self.return_pushButton = QtWidgets.QPushButton(addPasswordDialog)
        self.return_pushButton.setGeometry(QtCore.QRect(10, 410, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.return_pushButton.setFont(font)
        self.return_pushButton.setObjectName("return_pushButton")

        #run style function
        self.style()

        self.retranslateUi(addPasswordDialog)
        QtCore.QMetaObject.connectSlotsByName(addPasswordDialog)

    def style(self):
        self.email_lineEdit.setStyleSheet("color: rgb(0, 0, 0); background-color: rgb(255, 255, 255);")
        self.username_lineEdit.setStyleSheet("color: rgb(0, 0, 0); background-color: rgb(255, 255, 255);")
        self.appName_lineEdit.setStyleSheet("color: rgb(0, 0, 0); background-color: rgb(255, 255, 255);")
        self.password_lineEdit.setStyleSheet("color: rgb(0, 0, 0); background-color: rgb(255, 255, 255);")
        self.feedback_label.setStyleSheet("color: rgb(226, 0, 0);")
        self.save_pushButton.setStyleSheet("background-color: rgb(85, 85, 255); color: rgb(255, 255, 255);")
        self.clear_pushButton.setStyleSheet("background-color: rgb(85, 85, 255); color: rgb(255, 255, 255);")
        self.add_a_password_text.setStyleSheet("font-weight: bold;")
        self.creation_date_dateEdit.setStyleSheet("color: rgb(0, 0, 0); background-color: rgb(255, 255, 255);")
        self.enable_disable_dare_pushButton.setStyleSheet("background-color: rgb(226, 0, 0); color: rgb(255, 255, 255);")
        self.return_pushButton.setStyleSheet("background-color: rgb(85, 85, 255); color: rgb(255, 255, 255);")

    def retranslateUi(self, addPasswordDialog):
        _translate = QtCore.QCoreApplication.translate
        addPasswordDialog.setWindowTitle(_translate("addPasswordDialog", "Password Manager - Add a Password"))
        self.accountCreationDate_text.setText(_translate("addPasswordDialog", "Account Creation date:"))
        self.eMail_text.setText(_translate("addPasswordDialog", "E-Mail:"))
        self.username_text.setText(_translate("addPasswordDialog", "Username:"))
        self.password_text.setText(_translate("addPasswordDialog", "Password:"))
        self.appName_text.setText(_translate("addPasswordDialog", "App Name:"))
        self.feedback_label.setText(_translate("addPasswordDialog", ""))
        self.save_pushButton.setText(_translate("addPasswordDialog", "Save"))
        self.clear_pushButton.setText(_translate("addPasswordDialog", "Clear"))
        self.add_a_password_text.setText(_translate("addPasswordDialog", "Add a Password"))
        self.enable_disable_dare_pushButton.setText(_translate("addPasswordDialog", "X"))
        self.return_pushButton.setText(_translate("addPasswordDialog", "return"))