from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_clearAllDataDialog(object):
    def setupUi(self, clearAllDataDialog):
        clearAllDataDialog.setObjectName("clearAllDataDialog")
        clearAllDataDialog.setFixedSize(953, 381)
        clearAllDataDialog.setStyleSheet("background-color: rgb(85, 170, 255); color: rgb(255, 255, 255);")
        clearAllDataDialog.setWindowFlag(QtCore.Qt.WindowContextHelpButtonHint, False)
        clearAllDataDialog.setWindowIcon(QtGui.QIcon('sources\window_icon.ico'))

        self.clear_all_data_text = QtWidgets.QLabel(clearAllDataDialog)
        self.clear_all_data_text.setGeometry(QtCore.QRect(10, 10, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.clear_all_data_text.setFont(font)
        self.clear_all_data_text.setObjectName("clear_all_data_text")
        self.line = QtWidgets.QFrame(clearAllDataDialog)
        self.line.setGeometry(QtCore.QRect(0, 60, 251, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.main_groupBox = QtWidgets.QGroupBox(clearAllDataDialog)
        self.main_groupBox.setGeometry(QtCore.QRect(10, 90, 931, 261))
        self.main_groupBox.setTitle("")
        self.main_groupBox.setObjectName("main_groupBox")
        self.username_lineEdit = QtWidgets.QLineEdit(self.main_groupBox)
        self.username_lineEdit.setGeometry(QtCore.QRect(10, 30, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.username_lineEdit.setFont(font)
        self.username_lineEdit.setObjectName("username_lineEdit")
        self.username_text = QtWidgets.QLabel(self.main_groupBox)
        self.username_text.setGeometry(QtCore.QRect(10, 10, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.username_text.setFont(font)
        self.username_text.setObjectName("username_text")
        self.password_lineEdit = QtWidgets.QLineEdit(self.main_groupBox)
        self.password_lineEdit.setGeometry(QtCore.QRect(330, 30, 441, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.password_lineEdit.setFont(font)
        self.password_lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_lineEdit.setObjectName("password_lineEdit")
        self.password_text = QtWidgets.QLabel(self.main_groupBox)
        self.password_text.setGeometry(QtCore.QRect(330, 10, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.password_text.setFont(font)
        self.password_text.setObjectName("password_text")
        self.sheck_pushButton = QtWidgets.QPushButton(self.main_groupBox)
        self.sheck_pushButton.setGeometry(QtCore.QRect(800, 30, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sheck_pushButton.setFont(font)
        self.sheck_pushButton.setObjectName("sheck_pushButton")
        self.login_feedback_label = QtWidgets.QLabel(self.main_groupBox)
        self.login_feedback_label.setGeometry(QtCore.QRect(330, 70, 591, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.login_feedback_label.setFont(font)
        self.login_feedback_label.setObjectName("login_feedback_label")
        self.hide_show_password_pushButton = QtWidgets.QPushButton(self.main_groupBox)
        self.hide_show_password_pushButton.setGeometry(QtCore.QRect(730, 40, 31, 21))
        self.hide_show_password_pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("sources/hide_eye.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.hide_show_password_pushButton.setIcon(icon)
        self.hide_show_password_pushButton.setIconSize(QtCore.QSize(30, 30))
        self.hide_show_password_pushButton.setObjectName("hide_show_password_pushButton")
        self.clear_all_data_pushButton = QtWidgets.QPushButton(self.main_groupBox)
        self.clear_all_data_pushButton.setGeometry(QtCore.QRect(690, 180, 201, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.clear_all_data_pushButton.setFont(font)
        self.clear_all_data_pushButton.setObjectName("clear_all_data_pushButton")
        self.clear_data_feedback_label = QtWidgets.QLabel(self.main_groupBox)
        self.clear_data_feedback_label.setGeometry(QtCore.QRect(370, 200, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.clear_data_feedback_label.setFont(font)
        self.clear_data_feedback_label.setObjectName("clear_data_feedback_label")
        self.attention_groupBox = QtWidgets.QGroupBox(clearAllDataDialog)
        self.attention_groupBox.setGeometry(QtCore.QRect(200, 80, 591, 131))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.attention_groupBox.setFont(font)
        self.attention_groupBox.setObjectName("attention_groupBox")
        self.attention_textBrowser = QtWidgets.QTextBrowser(self.attention_groupBox)
        self.attention_textBrowser.setGeometry(QtCore.QRect(20, 40, 551, 71))
        self.attention_textBrowser.setObjectName("attention_textBrowser")
        self.continue_pushButton = QtWidgets.QPushButton(self.attention_groupBox)
        self.continue_pushButton.setGeometry(QtCore.QRect(170, 80, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.continue_pushButton.setFont(font)
        self.continue_pushButton.setObjectName("continue_pushButton")

        self.main_groupBox.hide()

        #style function
        self.style()

        self.retranslateUi(clearAllDataDialog)
        QtCore.QMetaObject.connectSlotsByName(clearAllDataDialog)

    def style(self):
        self.clear_all_data_text.setStyleSheet("font-weight: bold;")
        self.main_groupBox.setStyleSheet("border: solid rgb(85, 170, 255)")
        self.username_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255); color: rgb(0, 0, 0);")
        self.password_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255); color: rgb(0, 0, 0);")
        self.sheck_pushButton.setStyleSheet("background-color: rgb(85, 85, 255); border: solid rgb(0, 0, 0);")
        self.login_feedback_label.setStyleSheet("color: rgb(170, 0, 0);")
        self.hide_show_password_pushButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.clear_all_data_pushButton.setStyleSheet("background-color: rgb(170, 0, 0);")
        self.clear_data_feedback_label.setStyleSheet("color: rgb(0, 134, 0);")
        self.attention_textBrowser.setStyleSheet("border: 0;")
        self.continue_pushButton.setStyleSheet("background-color: rgb(85, 85, 255);")


    def retranslateUi(self, clearAllDataDialog):
        _translate = QtCore.QCoreApplication.translate
        clearAllDataDialog.setWindowTitle(_translate("clearAllDataDialog", "Control Panel - Clear all data"))
        self.clear_all_data_text.setText(_translate("clearAllDataDialog", "Clear All Data:"))
        self.username_lineEdit.setText(_translate("clearAllDataDialog", ""))
        self.username_text.setText(_translate("clearAllDataDialog", "Username:"))
        self.password_text.setText(_translate("clearAllDataDialog", "Password:"))
        self.sheck_pushButton.setText(_translate("clearAllDataDialog", "Sheck"))
        self.login_feedback_label.setText(_translate("clearAllDataDialog", ""))
        self.clear_all_data_pushButton.setText(_translate("clearAllDataDialog", "Clear All data..."))
        self.clear_data_feedback_label.setText(_translate("clearAllDataDialog", ""))
        self.attention_groupBox.setTitle(_translate("clearAllDataDialog", "Please be Aware!"))
        self.attention_textBrowser.setHtml(_translate("clearAllDataDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">After you agree to the operation, all your data will be lost forever.</span></p></body></html>"))
        self.continue_pushButton.setText(_translate("clearAllDataDialog", "continue..."))